### PR TITLE
Added exception for album folder recordName

### LINKED ISSUE #150: albumNameEnc error?
Hello, I just did a fresh install of windows 10, I also tried this on centos. Both give the same error bellow: 

```
Traceback (most recent call last):
  File "icloudpd.py", line 5, in <module>
    main()
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Provision\Desktop\icloud_photos_downloader-master\icloudpd\base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyicloud_ipd\services\photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'
```

### PR DESCRIPTION
**Pull request by Vlad1mir-D**
Fix https://github.com/ndbroadbent/icloud_photos_downloader/issues/150

### CODE REVIEW

**Review by menkej — APPROVED** [review]
Edit: I have do have '----Project-Root-Folder----' in my iCloud as well now, so this change is necessary to run the photo-sync - especially the --list-albums - again.

**Comment by ndbroadbent** [comment]
Thanks! I haven't tested this but it looks fine to me! Will merge and update to use it

**Comment by ndbroadbent** [comment]
Oh actually I just remembed I use a different `pyicloud-ipd` branch, instead of `master`. Also it looks like I just needed to update and rebase to use the latest code from https://github.com/picklepete/pyicloud, or maybe even switch back to that instead of using a fork, since there seems to be some activity there now.

**Comment by ndbroadbent** [comment]
Argh sorry it's too much work for now. There were a lot of conflicts and it will be a lot of work to get all the tests passing again, but eventually I'd like to do that. I pushed a branch for now: https://github.com/ndbroadbent/icloud_photos_downloader/tree/original_pyicloud

For now I manually applied your change to the `pyicloud-ipd` branch and released a new version

**Comment by Appelg** [comment]
Is it possible to get a docker image from that branch?

**Pull request merged**
